version: '2.1'

services:
  app:
    hostname: "Todo"
    build: 
      context: "docker"
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www"
    network_mode: bridge
    links: 
      - database:database
  database:
    platform: linux/x86_64
    image: mysql:5.7.43
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=symfony
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    expose:
      - 3036
    network_mode: bridge
